meta:
  organization: "PennState Health"
  service_name: "AI stroke navigator"
  site: "Hershey Medical Center"
  version: "1.0"
  description: "Post-discharge stroke care follow-up assessment"

greeting:
  template: >
    Good {timeofday} {honorific} {patient_name}. [pause=100] I am an AI stroke navigator calling from {organization}. [pause=100]
    I understand you recently had an ischemic stroke and received care at {site}. [pause=100]
    I'm going to ask a few questions to see how you're doing after discharge. [pause=100]
    I can't answer questions during this call, but I'll record additional requests at the end. [pause=100]
    With your consent, this call will be recorded for care documentation. 
  variables:
    - timeofday     # computed: morning/afternoon/evening
    - honorific     # UI input: "Mr." or "Ms."
    - patient_name  # UI input
    - organization  # from meta
    - site         # from meta

flow:
  - key: consent
    type: confirm
    prompt: "Do you consent to proceed with this recorded call?"
    on_deny: >
      I understand. [pause=100] We won't proceed with the call. [pause=100]
      If this is an emergency, please call your local emergency number or 911. [pause=100]
      If you'd like to speak with someone from our care team, please call the main hospital number. [pause=100]
      Thank you and goodbye.

  - key: know_ischemic
    type: confirm
    prompt: "Do you know what an ischemic stroke is?"
    on_deny: >
      An ischemic stroke happens when a blood vessel supplying blood to the brain is blocked, which can cause brain cells to be damaged. [pause=400]
      Knowing this can help with understanding your care plan.
    on_affirm: "Great! [pause=100] We'll proceed to the next question."

  - key: describe_condition
    type: free
    prompt: "Please share in your own words what you understand about your condition."

  - section: "General Well-Being"
  
  - key: general_feeling
    type: free
    prompt: "How have you been feeling overall since your hospital discharge?"
  
  - key: new_symptoms
    type: free
    prompt: "Have you noticed any new or worsening symptoms since discharge? This could include weakness, speech problems, vision changes, balance issues, or anything else that concerns you."
  
  - key: pain_fatigue_mood
    type: free
    prompt: "Are you experiencing any pain, headaches, unusual fatigue, anxiety, or changes in your mood?"
  
  - key: additional_concerns
    type: free
    prompt: "Do you have any other questions or concerns you'd like me to note for your care team?"

wrapup:
  message: >
    Thank you for taking the time to speak with me today. I've recorded all of your responses, 
    and a member of our clinical care team will review them and follow up with you if needed.
    
    Remember, if you experience any new stroke symptoms such as sudden weakness, speech problems, 
    vision changes, severe headache, or loss of balance, call 911 immediately.
    
    For non-urgent questions, you can always contact your primary care provider or our stroke care team.
    
    Take care, and thank you again for your time. Goodbye.

emergency_disclaimer: >
  If you are experiencing a medical emergency or new stroke symptoms right now, 
  please hang up and call 911 immediately.

stroke_warning_signs:
  - "Sudden weakness or numbness in face, arm, or leg, especially on one side"
  - "Sudden confusion or trouble speaking or understanding speech"
  - "Sudden trouble seeing in one or both eyes"
  - "Sudden severe headache with no known cause"
  - "Sudden trouble walking, dizziness, or loss of balance"

